### ISSUE TITLE
node app.js的时候报错了

### ISSUE THREAD

**Issue by bestsamcn** [cllgeek/movie-project#1]
![qq 20160826152110](https://cloud.githubusercontent.com/assets/17873080/17997396/d5b5f30a-6ba0-11e6-9b22-c866077e2673.png)
如图，第一次玩，也不知道哪里错了

**Comment by cllgeek** [comment]
给你个stackoverflow上的地址吧,估计是mongodb没开启来,http://stackoverflow.com/questions/36400233/connect-econnrefused-127-0-0-127017

**Comment by bestsamcn** [comment]
thx

**Comment by cllgeek** [comment]
可能是你定义movie的schema的时候类型写错了,你检查一下movie的schema
